module.exports = {
  NO_DATA: 'ERR_NO_DATA',
  LOGIN_FAIL: 'LOGIN_FAIL',
  NOT_LOGGED: 'NOT_LOGGED',
  ADD_INFOR_FAILED: 'ADD_INFOR_FAILED',
  REGISTERED_FAILED: 'REGISTERED_FAILED',
  SEND_CODE_FAILED: 'SEND_CODE_FAILED',
  VERIFY_FAILED: 'VERIFY_FAILED',
  ACTIVATE_FAILED: 'ACTIVATE_FAILED'
};
